const BestSellingHome = [
    {
        id: "1",
        image: "images/camera 1.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN16,085.1",
        button: "Add to cart"
       
    },
    {
        id: "2",
        image: "images/camera 3.avif",
        describe: "A full-frame mirror camera",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "31,243",
        kobo: ".20",
        formal: "NGN38,425,36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN35,155.9",
        button: "Add to cart"
    },
    {
        id: "3",
        image: "images/black speaker.jpg",
        describe: "Compact speakers designed",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "3,820",
        kobo: ".99",
        formal: "NGN10,330,36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN14,065.4",
        button: "Add to cart"
    },
    {
        id: "4",
        image: "images/camera 1.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "20,673",
        kobo: ".10",
        formal: "NGN40,785.36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN60,595.1",
        button: "Add to cart"
    },
    {
        id: "5",
        image: "images/3d-speaker.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,003",
        kobo: ".15",
        formal: "NGN15,905.36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN16,895.1",
        button: "Add to cart"
    },
    {
        id: "6",
        image: "images/acoustic-speakers.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "16,453",
        kobo: ".55",
        formal: "NGN30,575.36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN35,679.1",
        button: "Add to cart"
    },
    {
        id: "7",
        image: "images/earphones-with-case.avif",
        describe: "A full-frame DSLR 45.7MP... ",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "6,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "8",
        image: "images/game 1.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        choice: "Choice",
        shipping: "N19,000.25",
        total: "NGN16,085.1",
        button: "Add to cart"
    }
];

export default BestSellingHome;