const SuperDealsHome = [
    {
        id: "1",
        image: "images/game 6.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "2",
        image: "images/game 7.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "3",
        image: "images/game 11.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "4",
        image: "images/dvd-player-isolated.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "5",
        image: "images/game 6.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "N5,425.54",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "6",
        image: "images/game 7.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "N5,425.54",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "7",
        image: "images/game 11.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "N5,425.54",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "8",
        image: "images/dvd-player-isolated.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        promo: "-80%",
        choice: "Choice",
        shipping: "N5,425.54",
        total: "NGN16,085.1",
        button: "Add to cart"
    }
];

export default SuperDealsHome;