const sales = [
    {
        id: "1",
        image: "images/camera 1.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
       
    },
    {
        id: "2",
        image: "images/camera 3.avif",
        describe: "A full-frame mirror camera",
        star: "⭐⭐⭐⭐⭐",
        sold: "1000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "31,243",
        kobo: ".20",
        formal: "NGN38,425,36",
        rating: "SuperDeal",
        promo: "-10%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN35,155.9",
        button: "Add to cart"
    },
    {
        id: "3",
        image: "images/black speaker.jpg",
        describe: "Compact speakers designed",
        star: "⭐⭐⭐⭐⭐",
        sold: "20000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "3,820",
        kobo: ".99",
        formal: "NGN10,330,36",
        rating: "SuperDeal",
        promo: "-30%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN14,065.4",
        button: "Add to cart"
    },
    {
        id: "4",
        image: "images/camera 1.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "15000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "20,673",
        kobo: ".10",
        formal: "NGN40,785.36",
        rating: "SuperDeal",
        promo: "-40%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN60,595.1",
        button: "Add to cart"
    },
    {
        id: "5",
        image: "images/3d-speaker.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "1500+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,003",
        kobo: ".15",
        formal: "NGN15,905.36",
        rating: "SuperDeals",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,895.1",
        button: "Add to cart"
    },
    {
        id: "6",
        image: "images/acoustic-speakers.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "5000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "16,453",
        kobo: ".55",
        formal: "NGN30,575.36",
        rating: "SuperDeal",
        promo: "-60%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN35,679.1",
        button: "Add to cart"
    },
    {
        id: "7",
        image: "images/earphones-with-case.avif",
        describe: "A full-frame DSLR 45.7MP... ",
        star: "⭐⭐⭐⭐⭐",
        sold: "20000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "6,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "8",
        image: "images/game 1.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "9",
        image: "images/game 3.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "10",
        image: "images/game 10.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "11",
        image: "images/home-appliance.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "12",
        image: "images/iphones.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "13",
        image: "images/realistic-house.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "14",
        image: "images/remote-control.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "15",
        image: "images/smartphone-earphones.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "16",
        image: "images/speaker.avif",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "17",
        image: "images/game 6.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "18",
        image: "images/game 7.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "19",
        image: "images/game 11.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button: "Add to cart"
    },
    {
        id: "20",
        image: "images/dvd-player-isolated.jpg",
        describe: "A full-frame DSLR 45.7MP...",
        star: "⭐⭐⭐⭐⭐",
        sold: "10000+",
        tag: "Top Selling",
        currency: "NGN",
        amount: "5,243",
        kobo: ".25",
        formal: "NGN15,425,36",
        rating: "SuperDeal",
        promo: "-80%",
        choice: "Choice",
        shipping: "Fre shipping over",
        total: "NGN16,085.1",
        button:"Add to cart"
    }
];

export default sales;